//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproject
    {
        public int projectId { get; set; }
        public string projectName { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
